In [21]:
import pandas as pd
from astroquery.vizier import Vizier
Vizier.ROW_LIMIT = 40000 # makes sure you don't lose columns--make sure the number of rows isn't equal to this or you might have to increase it

In [19]:
# query Spitzer (code = II/368) centered on NGC 1977 with a radius of 20 arcminutes
result = Vizier.query_region("NGC 1977", radius="0d20m0s", catalog='II/368') 
result

TableList with 1 tables:
	'0:II/368/sstsl2' with 37 column(s) and 4265 row(s)

In [24]:
# convert astroquery TableList to pandas DataFrame
dataframe = result[0].to_pandas()
dataframe

,RAJ2000,DEJ2000,Name,Nbands,F3.6Ap1,e_F3.6Ap1,F3.6Ap2,e_F3.6Ap2,F4.5Ap1,e_F4.5Ap1,...,FSx3.6,FSx4.5,FSx5.8,FSx8.0,SMID,REGID,_2MASS,RAWdeg,DEWdeg,WISEA
0,83.738327,-5.139974,SSTSL2 J053457.19-050823.9,6,11581.000000,8.3243,11733.000000,10.8280,7865.200195,14.0170,...,0,0,0,0,40044081,40044081-89,1194777152,83.73835,-5.139973,WISEA
1,83.724561,-5.132122,SSTSL2 J053453.89-050755.6,3,308.350006,3.6642,290.480011,6.1200,215.929993,8.0208,...,0,0,<NA>,<NA>,40044081,40044081-89,1194777183,NaN,NaN,WISEA
2,83.732786,-5.139197,SSTSL2 J053455.86-050821.1,6,6574.500000,6.2653,6533.000000,7.9549,3602.800049,9.0585,...,0,0,0,0,40044081,40044081-89,1194777155,83.73277,-5.139211,WISEA
3,83.734880,-5.134609,SSTSL2 J053456.37-050804.5,3,183.559998,4.0576,270.920013,7.1830,114.300003,7.9443,...,0,0,<NA>,<NA>,40044081,40044081-89,<NA>,83.73520,-5.134747,WISEA
4,83.687402,-5.113760,SSTSL2 J053444.97-050649.5,6,29166.000000,11.1650,29255.000000,11.5520,22374.000000,11.2470,...,0,0,0,<NA>,40044081,40044081-89,1194777218,83.68742,-5.113760,WISEA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4260,83.731752,-4.504258,SSTSL2 J053455.62-043015.3,2,77.143997,1.7624,65.947998,2.6130,56.974998,2.0473,...,0,0,<NA>,<NA>,40044081,40044081-96,<NA>,NaN,NaN,WISEA
4261,83.736859,-4.499704,SSTSL2 J053456.84-042958.9,2,36.952999,1.7438,31.340000,2.7820,26.927999,2.0152,...,0,0,<NA>,<NA>,40044081,40044081-96,<NA>,NaN,NaN,WISEA
4262,83.711774,-4.506756,SSTSL2 J053450.82-043024.3,2,57.905998,2.0284,0.090560,3.1755,44.544998,2.0730,...,0,0,<NA>,<NA>,40044081,40044081-96,<NA>,NaN,NaN,WISEA
4263,83.716079,-4.517449,SSTSL2 J053451.85-043102.8,3,62.613998,2.1199,107.129997,3.5142,42.798000,2.0858,...,0,0,<NA>,<NA>,40044081,40044081-96,<NA>,83.71600,-4.517771,WISEA
4264,83.736688,-4.495315,SSTSL2 J053456.80-042943.1,2,36.480999,1.4826,40.990002,2.3446,41.527000,1.8523,...,0,0,<NA>,<NA>,40044081,40044081-96,<NA>,NaN,NaN,WISEA